name: amazing_icons
description: A flutter package that provides a collection of customizable icons for various use cases.
version: 3.0.0
repository: https://github.com/O-Nicks/amazing_icons

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  jovial_svg: ^1.1.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - icons/si/payment/

  fonts:
    - family: AmazingIconFilled
      fonts:
        - asset: fonts/AmazingIconFilled.ttf

    - family: AmazingIconOutlined
      fonts:
        - asset: fonts/AmazingIconOutlined.ttf

    - family: AmazingIconBroken
      fonts:
        - asset: fonts/AmazingIconBroken.ttf

    - family: AmazingIconBulkBg
      fonts:
        - asset: fonts/AmazingIconBulkBg.ttf

    - family: AmazingIconBulkFg
      fonts:
        - asset: fonts/AmazingIconBulkFg.ttf

    - family: AmazingIconTwotoneBg
      fonts:
        - asset: fonts/AmazingIconTwotoneBg.ttf

    - family: AmazingIconTwotoneFg
      fonts:
        - asset: fonts/AmazingIconTwotoneFg.ttf
